version: '3.8'
services:
  centos7:
    image: pycontribs/centos:7
    container_name: centos7
    restart: always
    tty: true

  ubuntu:
    image: pycontribs/ubuntu
    container_name: ubuntu
    restart: always
    tty: true

  fedora:
    image: pycontribs/fedora
    container_name: fedora
    restart: always
    tty: true