---
  - name: Print os facts
    hosts: all
    tasks:
      - name: Print OS
        debug:
          msg: "{{ ansible_distribution }}"
      - name: Print version
        debug:
          msg: "{{ ansible_version.full }}"    
      - name: Print fact
        debug:
          msg: "{{ some_fact }}"